### ISSUE TITLE
Error Transferring Libra Coins

### ISSUE THREAD

**Issue by Ren14** [kulapio/libra-core#8] opened 2019-09-04 19:07 UTC
Helo ! 

When sending a transaction, I get the following error.
`validationStatusError: { code: 11, message: 'none' },`
Yesterday it was working correctly.

Thanks !

**Comment by totiz** [comment] 2019-09-07 04:06
@Ren14 Network just rest and we need to update the lib, https://community.libra.org/t/testnet-update-september-4th/1630. We hope to fix this soon.

**Comment by glachac** [comment] 2019-09-07 15:19
@totiz  I have two PR's at perfectmak/libra-core that should both apply here as well:

 https://github.com/perfectmak/libra-core/pull/43
https://github.com/perfectmak/libra-core/pull/44

Nothing to fix the transfer issue though, as I'm not sure what the root cause is.  I didn't think LCS made it to the testnet yet.

**Comment by totiz** [comment] 2019-09-10 05:23
Just fixed with this release https://github.com/kulapio/libra-core/releases/tag/v1.0.17

**Closed by totiz** 2019-09-10 05:23 UTC
