### ISSUE TITLE
Error in the example "Query Transaction with Sequence Number"

### ISSUE THREAD

**Issue by Ren14** [kulapio/libra-core#2] opened 2019-07-31 19:36 UTC
Hello !

When doing the example, I get the following error :

/var/www/html/libra_jwt/node_modules/kulap-libra/build/client/Decoder.js:47
        const signedTransaction = signedTransactionWP.getSignedTransaction();
                                                      ^

TypeError: Cannot read property 'getSignedTransaction' of undefined
    at ClientDecoder.decodeSignedTransactionWithProof (/var/www/html/libra_jwt/node_modules/kulap-libra/build/client/Decoder.js:47:55)
    at responseTask (/var/www/html/libra_jwt/node_modules/kulap-libra/build/client/index.js:127:38)
    at Object.onReceiveStatus (/var/www/html/libra_jwt/node_modules/grpc/src/client_interceptors.js:1207:9)
    at InterceptingListener._callNext (/var/www/html/libra_jwt/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/var/www/html/libra_jwt/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/var/www/html/libra_jwt/node_modules/grpc/src/client_interceptors.js:845:24)
[nodemon] app crashed - waiting for file changes before starting...

can you verify it?
Thanks !

**Comment by totiz** [comment] 2019-08-02 07:41
Could you specific the example or codes that produce this error, thanks.

**Comment by totiz** [comment] 2019-08-03 03:10
Ok I found it, the problem is fixed with https://github.com/kulapio/libra-core/pull/3, bug from account state changes on libra network https://community.libra.org/t/testnet-update-july-31st/1448/2.

**Closed by totiz** 2019-08-03 03:10 UTC
